In [1]:
import nltk
import re
import pandas as pd

msg = pd.read_csv(r"C:\Users\rauna\codes\datasets\SMSSpamCollection", sep ="\t", names = ["label","message"])

In [2]:
msg.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
msg["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
from nltk import WordNetLemmatizer
lm = WordNetLemmatizer()
from nltk.corpus import stopwords

In [5]:
corpus = []

for i in range(0,len(msg)):
    review = re.sub('[^a-zA-Z]',' ', msg["message"][i])
    review = review.lower()
    review = review.split()
    review = [lm.lemmatize(word) for word in review if not word in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)
    

In [6]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

## Creating bag of words

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))

In [8]:
x = cv.fit_transform(corpus).toarray()

In [9]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [10]:
cv.vocabulary_

{'go': 768,
 'point': 1623,
 'crazy': 437,
 'available': 108,
 'bugis': 217,
 'great': 813,
 'world': 2440,
 'la': 1046,
 'cine': 340,
 'got': 804,
 'wat': 2351,
 'ok': 1479,
 'lar': 1059,
 'joking': 1003,
 'wif': 2403,
 'ok lar': 1481,
 'free': 693,
 'entry': 594,
 'wkly': 2426,
 'comp': 390,
 'win': 2408,
 'cup': 446,
 'final': 658,
 'st': 1970,
 'may': 1241,
 'text': 2079,
 'receive': 1728,
 'question': 1694,
 'std': 1985,
 'txt': 2189,
 'rate': 1707,
 'apply': 73,
 'free entry': 698,
 'entry wkly': 596,
 'std txt': 1986,
 'txt rate': 2195,
 'rate apply': 1708,
 'dun': 552,
 'say': 1814,
 'early': 559,
 'already': 47,
 'nah': 1379,
 'think': 2099,
 'usf': 2274,
 'life': 1118,
 'around': 84,
 'though': 2107,
 'freemsg': 705,
 'hey': 875,
 'darling': 464,
 'week': 2372,
 'word': 2435,
 'back': 127,
 'like': 1123,
 'fun': 724,
 'still': 1988,
 'tb': 2058,
 'xxx': 2468,
 'send': 1848,
 'even': 604,
 'brother': 208,
 'speak': 1955,
 'treat': 2168,
 'per': 1552,
 'request': 1759,
 'melle'

In [11]:
y = pd.get_dummies(msg["label"],dtype=int)
y = y.iloc[:,0].values
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.3)

In [13]:
from sklearn.naive_bayes import MultinomialNB

In [14]:
spam_detect = MultinomialNB().fit(x_train,y_train)

In [15]:
spam_detect

MultinomialNB()

In [16]:
y_pred = spam_detect.predict(x_test)

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
acc = accuracy_score


In [18]:
acc(y_test,y_pred)

0.9832535885167464

In [19]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       224
           1       0.99      0.99      0.99      1448

    accuracy                           0.98      1672
   macro avg       0.96      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672



## TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1,2))

In [23]:
x = tfidf.fit_transform(corpus)

In [24]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [26]:
spam_detect_tfidf = MultinomialNB().fit(x_train,y_train)

In [27]:
y_pred = spam_detect_tfidf.predict(x_test)

In [28]:
accuracy_score(y_test,y_pred)

0.9748803827751196

In [29]:
confusion_matrix(y_test,y_pred)

array([[ 183,   42],
       [   0, 1447]], dtype=int64)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90       225
           1       0.97      1.00      0.99      1447

    accuracy                           0.97      1672
   macro avg       0.99      0.91      0.94      1672
weighted avg       0.98      0.97      0.97      1672



We have done our modelling after transforming the data which causes the data leakage issue. So, we will now try to do the same process but we will do the train_test_split first and then transform them into BOW or TF-IDF

In [35]:
x_train,x_test, y_train,y_test = train_test_split(corpus,y,test_size=0.3)

In [ ]:
# we will use bow because we were getting more accuracy compare to tf-idf to check if there is any overfitting.
x_train = cv.fit_transform(x_train).toarray()
x_test = cv.transform(x_test).toarray()

In [38]:
spam_detect_bow_v2 = MultinomialNB().fit(x_train,y_train)

In [40]:
y_pred = spam_detect_bow_v2.predict(x_test)

In [41]:
accuracy_score(y_test,y_pred)

0.9826555023923444

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94       256
           1       0.98      1.00      0.99      1416

    accuracy                           0.98      1672
   macro avg       0.98      0.95      0.97      1672
weighted avg       0.98      0.98      0.98      1672

